sed s/back./0/g dataset0.dat >dataset1.dat
sed s/buffer_overflow./1/g dataset1.dat >dataset2.dat
sed s/ftp_write./2/g dataset2.dat >dataset3.dat
sed s/guess_passwd./3/g dataset3.dat >dataset4.dat
sed s/imap./4/g dataset4.dat >dataset5.dat
sed s/ipsweep./5/g dataset5.dat >dataset6.dat
sed s/land./6/g dataset6.dat >dataset7.dat
sed s/loadmodule./7/g dataset7.dat >dataset8.dat
sed s/multihop./8/g dataset8.dat >dataset9.dat
sed s/neptune./9/g dataset9.dat >dataset10.dat
sed s/nmap./10/g dataset10.dat >dataset11.dat
sed s/normal./11/g dataset11.dat >dataset12.dat                    
sed s/perl./12/g dataset12.dat >dataset13.dat
sed s/phf./13/g dataset13.dat >dataset14.dat
sed s/pod./14/g dataset14.dat >dataset15.dat
sed s/portsweep./15/g dataset15.dat >dataset16.dat
sed s/rootkit./16/g dataset16.dat >dataset17.dat
sed s/satan./17/g dataset17.dat >dataset18.dat
sed s/smurf./18/g dataset18.dat >dataset19.dat
sed s/spy./19/g dataset19.dat >dataset20.dat
sed s/teardrop./20/g dataset20.dat >dataset21.dat
sed s/warezclient./21/g dataset21.dat >dataset22.dat
sed s/warezmaster./22/g dataset22.dat >dataset23.dat